services:
  frontend:
    build: ./frontend
    image: thomascml/frontend-eventhub
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_started
  backend:
    build: ./backend
    image: thomascml/backend-eventhub
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./postgres/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
